kind = "web"
previewPath = "/"
title = "REVD STORE"
version = "1.0.0"
id = "artifacts/revd-store"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22341

[services.development]
run = "pnpm --filter @workspace/revd-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/revd-store", "run", "build" ]
serve = "static"
publicDir = "artifacts/revd-store/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22341"
BASE_PATH = "/"
